### ISSUE TITLE
这样为什么不会往上循环滚动？？？

### ISSUE THREAD

**Issue by Wang-Yang** [rockyxia/vue-superslide#3]
![image](https://user-images.githubusercontent.com/25840593/68445602-5319f400-0215-11ea-8fdf-4318e34c6e76.png)
![image](https://user-images.githubusercontent.com/25840593/68445615-5ca35c00-0215-11ea-93cf-de4380fa469c.png)

**Comment by rockyxia** [comment]
https://github.com/rockyxia/vue-superslide/issues/1#issuecomment-508425341

**Comment by Wang-Yang** [comment]
不报错

**Comment by Wang-Yang** [comment]
抱歉，配置错误。。。尴尬。。。因为后台数据只有4条，而vis参数设置了10，所以不会滚动。。。
