### ISSUE TITLE
无缝滚动的时候首位相接的时候会错位，不是无缝的，是噔一下切换了

### ISSUE THREAD

**Issue by LionlyloveK** [rockyxia/vue-superslide#6]

**Comment by rockyxia** [comment]
有在线预览地址么

**Comment by LionlyloveK** [comment]
> 有在线预览地址么

解决啦，是我加下边框的问题，去掉box-sizing就好啦

**Comment by rockyxia** [comment]
好的，我去https://rockyxia.github.io/vue-superslide/#/demo/picMarqueeLeft 看了下，好像没你说的问题
